---
title: "Counting Rules"
titleshort: "Counting Rules"
description: |
  Counting Rules
date: 2020-06-19
date_start: 2018-12-01
output:
  pdf_document:
    pandoc_args: '../_output_kniti_pdf.yaml'
    includes:
      in_header: '../preamble.tex'
  html_document:
    pandoc_args: '../_output_kniti_html.yaml'
    includes:
      in_header: '../hdga.html'
always_allow_html: true
urlcolor: blue
---

## Sample Space and Probability Examples

```{r global_options, include = FALSE}
try(source("../.Rprofile"))
```

`r text_shared_preamble_one`
`r text_shared_preamble_two`
`r text_shared_preamble_thr`

## Counting Rules

There are different experimental comes, and probabilities associated with different experimental outcomes.

To figure out what the probabilities associated with different experimental outcomes are, we need to first know what possible experimental outcomes exist in the sample space.

### Trivial Counting

Often, we do not need to employ additional mathematical tools, and can count directly  the number of experimental outcomes in a sample space.

If we *toss a quarter* once, there are two outcomes, heads vs tails, which are the two elements in the sample space.

- $S = \left\{H, T\right\}$
- Number of experimental outcomes: 2

If we *toss a six-sided dice* once, there are six possible outcomes from the six possible sides, which are the six elements in the sample space.

- $S = \left\{1,2,3,4,5,6\right\}$
- Number of experimental outcomes: 6

If four people are competing to be the next astronaut, the possible sample space of astronaut includes these four people.

- $S = \left\{P_1, P_2, P_3, P_4\right\}$
- Number of experimental outcomes: 3

If it is one month before the *presidential election*, and there are officially 4 people registered as presidential candidates who will be on the ballot, then there are four possible people who could be the president.

- $S = \left\{DT, GS, GJ, HC \right\}$
- Number of experimental outcomes: 4

The school basketball team will play 5 games this season. The team can only win or lose for each game. If we only care about the number of wins/loses, then there are $5+1=6$ possible experimental outcomes: they win no games, 1 game, 2 games, 3 games, 4 games, and 5 games.

- $S = \left\{0, 1, 2, 3, 4, 5 \right\}$
- Number of experimental outcomes: 6

Note that in all the examples above, specifying the number of experimental outcomes does not tell us the probability that each outcome will be realized by. The dice could be weighted and the quarter could have a heavier side. Then knowing that there are 2 sides to a quarter and six sides to a dice does not tell us what the chance of getting each side is. The fact that there are four presidential candidate does not mean that each has $25$ percent chance of winning. A better basketball team would have higher chances of winning more games than a worse team, but the sample space of all possible experimental outcomes would be the same

### Multi-Step Experiment

If we have a sequence of independent experiments, then each sequence of outcomes is a different experimental outcome, and the probability associated with each experimental outcome is determined by:

$$
P\left(\text{(outcome A experiment 1)} \cap \text{(outcome B experiment 2)}  \cap \text{(outcome C experiment 3)}\right) \\
 = P(A^{E_1}) \cdot P(B^{E_2}) \cdot P(C^{E_3})
$$

We discussed this in [Multiple-Step Experiment: Playing the Lottery Three times](https://fanwangecon.github.io/Stat4Econ/probability/htmlpdfr/lottery.html).

### Combination

### Permutation

- In the tossing quarter or tossing dice examples:
    + it could be that the quarter and dice are fair: if that is the case then the probability of getting each side of the dice is $\frac{1}{6}$, and the probability of getting each side of quarter is $\frac{1}{2}$.  In these cases, the probability that each experimental outcome happens is the same (uniform), and so the number of experimental outcomes is linked to the probability for each outcome.
    + But that is not generally true,
